---
title: "Fundamentos de arquitectura"
---

## ¿Qué es una arquitectura de software?


El término **arquitectura** tiene multiples significados según el contexto. En ingeniería de software/sistemas, ¿de qué hablamos cuando decimos **arquitectura software**? 

- ¿Nos referimos a una aplicación móvil?
- ¿A una librería software?
- ¿O una aplicación empresarial?
- ¿Tal vez una red de sensores desplegados en la ciudad junto a un centro (hub) de datos?
- ¿O simplemente el conjunto de diagramas de clases u casos de usos asociados?
- ¿Una red de *data centers* como los que posee Meta, Google, etc.?

Es importante definir, o al menos caracterizar, qué implica el diseño y desarrollo de una arquitectura de software. Especialmente si queremos dedicarnos al desarrollo de arquitecturas de software en el futuro. ¿Lo has pensado como profesión?

::: {.callout-tip icon=false}
## **Slide Deck** 

::: slides
[Conceptos, roles y compromisos](01-arquitectura-conceptos.qmd)
:::

:::

## Características de la arquitectura de software

Según [@richards2020], las dimensiones de una arquitecrua de software son:

- Estructura o estilo
- Características
- Decisiones o reglas
- Principios de diseño

Ahora nos cetramos en la dimensión de **características de la arquitectura**, donde se engloban todos aquellos criterios y requisitos no funcionales (nombres terminaddos en *idad*, como seguridad, fiabilidad, escalabildiad, etc.) para garantizar el correcto y deseable funcionamiento de un sistema.

::: {.callout-tip icon=false}
## **Slide Deck** 

::: slides
[Características](01-arquitectura-caracteristicas.qmd)
:::

:::


## Estructura de la arquitectura de software

La estructura o el estilo es otra dimensión de la arquitectura de software [@richards2020]. Quizás mucho más conocida y popular, y precisamente por eso, existe la errónea tendencia a reducir la arquitectura de software únicamente a la dimensión de la estructura o el estilo. Hablamos de arquitectura **en capas** o basada en **microservicios**, como si la estructura en sí misma abarcara toda la complejidad de una arquitectura de software.

::: {.callout-tip icon=false}
## **Slide Deck** 

::: slides
[Estilos de arquitectura](https://cgranell.github.io/ei1039/slides/TE2_estilos_arquitectura.html)
:::

:::

